config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"

  resources :events, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_commit :save_user_in_iterator, on: :create

  private

  # This is to save user in Iterator after user creation/signup
  def save_user_in_iterator
    UsersInIteratorService.new({user_id: id, user_email: email}).call
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # Add first_name and last_name in Devise users table from UI
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :first_name, :last_name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    # Event type A or B
    event_type = params[:event_type]

    # EventsInIteratorService saves Events in Iterator
    response = EventsInIteratorService.new({user_email: current_user.email, event_type: event_type}).call

    if response == 200
      # For Event B - If Events are created successfully in Iterator, move forward with Email trigger functionality
      if eligible_event_type.include?(event_type)
        camp_id = get_campaign_id
        return send_email(camp_id) if camp_id
      end
      flash.now[:success] = "Event #{event_type} created in iterator!!"
    else
      flash.now[:error] = "Event #{event_type} creation failed in iterator."
    end
    render turbo_stream: turbo_stream.replace("flash-messages", partial: "layouts/flash_message")
  end

  private

  def eligible_event_type
    ["B"]
  end

  # SetCampaignIdService executes 3 Iterator APIs to get campaign_id, which can be used in email trigger API
  # To avoid calling these APIs multiple times for every event B trigger,
  # I am storing campaign_id in session for a user so that it can be reused'''
  def get_campaign_id
    unless session["iterable_campaign_id"]
      session["iterable_campaign_id"] = SetCampaignIdService.new({user_id: current_user.id}).call
    end
    session["iterable_campaign_id"]
  end

  # SendEmailService sends Email to current user for Event B trigger
  def send_email(camp_id)
    response = SendEmailService.new({campaign_id: camp_id, user_email: current_user.email}).call

    if response == 200
      flash.now[:success] = "Event #{params[:event_type]} created in iterator and email sent to #{current_user.email}!!"
    else
      flash.now[:error] = "Event #{params[:event_type]} created in iterator but email failed."
    end
    render turbo_stream: turbo_stream.replace("flash-messages", partial: "layouts/flash_message")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<%= render template: "layouts/logout" %>
<div style="margin: 10em 30em; display: flex; align-items: center; justify-content: space-evenly;">
  <%= button_to "Create Event A", events_path(event_type: "A"), method: :post, style: "padding: 20px; background: lightblue; cursor: pointer;" %>
  <%= button_to "Create Event B", events_path(event_type: "B"), method: :post, style: "padding: 20px; background: lightblue; cursor: pointer;" %>
</div>

app/views/layouts/_flash_message.html.erb
<div id="flash-messages">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IteratorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/flash_message" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/logout.html.erb
<html>
  <body>
    <div style="width: 100%; height: 100px !important; margin-right: 10px !important; display: flex; justify-content: flex-end;">
      <%= link_to "Logout", destroy_user_session_path, style: "font-size: large;" %>
    </div>
    <%= yield %>
  </body>
</html>